name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时更新一次（比每天更频繁）
  workflow_dispatch:  # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # 输出到仓库根目录的 snake.svg 文件
          svg_out_path: snake.svg
          # 自定义贪吃蛇和背景点颜色（参考anka-afk的配色）
          color_snake: 'var(--color-foreground)'
          color_dots: 'var(--color-background)'

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update snake animation"
          add: "snake.svg"
